### PR TITLE
Merge with nvim-numbertoggle

### LINKED ISSUE #10: Common plugin goals
Hello,

I am maintaining https://github.com/nkakouros-original/numbers.nvim which does the same thing as your plugin here. Would you like to combine efforts into a single plugin?

### PR DESCRIPTION
**Pull request by sitiom**
I have combined the work that I have done with this plugin. This also includes the additional things:

- editorconfig file
- [stylua](https://github.com/JohnnyMorganz/StyLua) formatting check
- [selene](https://github.com/Kampfkarren/selene) linter
- [sumneko](https://github.com/sumneko/lua-language-server) config file
- [panvimdoc](https://github.com/kdheepak/panvimdoc) workflow to automatically generate vimdocs from the README.

Closes https://github.com/sitiom/nvim-numbertoggle/issues/10.

### CODE REVIEW

**Comment by agoodshort** [comment]
Any chance we can proceed with this PR?
I am pointing to `use({ "sitiom/numbers.nvim", branch = "numbertoggle", config = function() require("numbers").setup() end })` and did not face any issues so far

**Comment by nkakouros** [comment]
@goodshort Thanks for reminding, I though I had merged this for some reason.

@sitiom Are you still interested in the merge? Is there anything we should add to the PR? Should we do it the other way around?

**Comment by sitiom** [comment]
I'm good with keeping my plugin as simple as it is. You can have these changes.

**Comment by nkakouros** [comment]
OK. Then, I will close this PR. Both plugins work fine, it is just a matter of which the user finds first. I might pick some of the changes here in the future.

**Pull request closed without merging**
